let allTrains=[], visibleTrains=[], selected=null, pending=null, method='UPI';
let user=null, profile=null;
const $=id=>document.getElementById(id);
const cities=['Bengaluru','Chennai','Delhi','Mumbai','Hyderabad','Pune','Secunderabad','Coimbatore','Ernakulam','Mangaluru','Jaipur','Kolkata'];

function requireDb(){ if(!supabaseClient){alert('Open web/config.js and add your Supabase URL and anon/publishable key.'); return false;} return true; }
function setToday(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$('date').value=d.toISOString().slice(0,10)}
async function init(){
  if(!requireDb()) return;
  setToday();
  const {data:{session}}=await supabaseClient.auth.getSession();
  if(session){await loadUser(session.user)}
  supabaseClient.auth.onAuthStateChange(async (_event,session)=>{if(session) await loadUser(session.user); else {user=null;profile=null;nav();history();}});
  await loadTrains(); nav(); history();
}
async function loadUser(u){user=u; const {data:p}=await supabaseClient.from('profiles').select('id,name,email,mobile,role').eq('id',u.id).single(); profile=p||null; nav(); history();}
async function loadTrains(){const {data,error}=await supabaseClient.from('trains').select('*').order('id');if(error){$('list').innerHTML='<div class="empty">Database error: '+escapeHtml(error.message)+'</div>';return} allTrains=(data||[]).map(mapTrain);visibleTrains=allTrains;render(allTrains)}
function mapTrain(x){return {id:x.id,trainNumber:x.train_number,trainName:x.train_name,source:x.source,destination:x.destination,departure:x.departure,arrival:x.arrival,image:x.image,acSeats:x.ac_seats,sleeperSeats:x.sleeper_seats,generalSeats:x.general_seats,fareAc:Number(x.fare_ac),fareSleeper:Number(x.fare_sleeper),fareGeneral:Number(x.fare_general)}}
function mode(x,b){document.querySelectorAll('.tabs button').forEach(y=>y.classList.remove('active'));b.classList.add('active');$('routeBox').classList.toggle('hidden',x!=='route');$('trainBox').classList.toggle('hidden',x!=='train')}
function places(w){const q=$(w).value.trim().toLowerCase();const a=cities.filter(x=>x.toLowerCase().includes(q)).slice(0,6);$(w+'Sug').innerHTML=q?a.map(x=>`<div onclick="pick('${w}','${x}')">📍 ${x}</div>`).join(''):''}
function pick(w,x){$(w).value=x;$(w+'Sug').innerHTML=''} function swap(){const x=$('from').value;$('from').value=$('to').value;$('to').value=x}
async function searchRoute(){const f=$('from').value.trim(),t=$('to').value.trim();if(!f||!t)return alert('Enter both From and To cities.');if(f.toLowerCase()===t.toLowerCase())return alert('From and To cities must be different.');const {data,error}=await supabaseClient.from('trains').select('*').ilike('source',f).ilike('destination',t).order('id');if(error)return alert(error.message);visibleTrains=(data||[]).map(mapTrain);$('result').textContent=`${f} → ${t}`;render(visibleTrains);$('trains').scrollIntoView({behavior:'smooth'})}
function trainSug(){const q=$('query').value.trim().toLowerCase();const a=allTrains.filter(x=>x.trainName.toLowerCase().includes(q)||x.trainNumber.includes(q)).slice(0,8);$('trainSug').innerHTML=q?a.map(x=>`<div onclick="pickTrain('${x.trainNumber}')">🚆 ${escapeHtml(x.trainName)}<small>${x.trainNumber} • ${escapeHtml(x.source)} → ${escapeHtml(x.destination)}</small></div>`).join(''):''}
function pickTrain(n){const x=allTrains.find(y=>y.trainNumber===n);if(x){$('query').value=x.trainName;$('trainSug').innerHTML=''}}
async function searchTrain(){const q=$('query').value.trim();if(!q)return alert('Enter a train name or train number.');const {data,error}=await supabaseClient.from('trains').select('*').or(`train_name.ilike.%${q}%,train_number.ilike.%${q}%`).order('id');if(error)return alert(error.message);visibleTrains=(data||[]).map(mapTrain);$('result').textContent='Train search: '+q;render(visibleTrains);$('trains').scrollIntoView({behavior:'smooth'})}
function render(a){$('list').innerHTML=a.length?a.map(x=>`<div class="train"><img src="${x.image}" alt="Train"><div><b>${escapeHtml(x.trainName)}</b><small>Train No. ${x.trainNumber}</small></div><div><b>${x.departure}</b><small>${escapeHtml(x.source)}</small></div><div><b>${x.arrival}</b><small>${escapeHtml(x.destination)}</small></div><div><b>Seats</b><small>AC ${x.acSeats} • Sleeper ${x.sleeperSeats} • General ${x.generalSeats}</small></div><button onclick="book(${x.id})">Book</button></div>`).join(''):'<div class="empty">No trains found for this search.</div>'}
function book(id){if(!user)return login('Login before booking.');selected=allTrains.find(x=>x.id==id);if(!selected)return alert('Train not found.');$('selected').innerHTML=`<img src="${selected.image}" class="large" alt="Train"><h2>${escapeHtml(selected.trainName)}</h2><p>Train No. ${selected.trainNumber}</p><h3>${escapeHtml(selected.source)} → ${escapeHtml(selected.destination)}</h3><p>${selected.departure} → ${selected.arrival}</p><p>AC ${selected.acSeats} • Sleeper ${selected.sleeperSeats} • General ${selected.generalSeats}</p>`;$('booking').classList.remove('hidden');$('payment').classList.add('hidden');$('ticket').classList.add('hidden');$('booking').scrollIntoView({behavior:'smooth'});fare()}
function fare(){if(!selected)return;const c=$('class').value;if(!c){$('fare').textContent='Select class';return}const f=Number(c==='AC'?selected.fareAc:c==='Sleeper'?selected.fareSleeper:selected.fareGeneral);$('fare').textContent='Fare: ₹'+f.toFixed(2)}
$('bookForm').onsubmit=e=>{e.preventDefault();if(!selected||!user)return;const c=$('class').value;if(!c)return alert('Select a class.');const f=Number(c==='AC'?selected.fareAc:c==='Sleeper'?selected.fareSleeper:selected.fareGeneral);if(Number($('age').value)<1)return alert('Enter a valid age.');if(!/^\d{10}$/.test($('contact').value.trim()))return alert('Enter a valid 10-digit contact number.');pending={train_id:selected.id,passenger_name:$('pname').value.trim(),age:Number($('age').value),gender:$('gender').value,contact:$('contact').value.trim(),travel_class:c,travel_date:$('date').value,fare:f};$('summary').innerHTML=`<h2>${escapeHtml(selected.trainName)}</h2><p>${escapeHtml(selected.source)} → ${escapeHtml(selected.destination)} • ${c}</p><h2>₹${f.toFixed(2)}</h2>`;$('payment').classList.remove('hidden');$('payment').scrollIntoView({behavior:'smooth'})}
function paymode(m,b){method=m;document.querySelectorAll('.methods button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('payFields').innerHTML=m==='UPI'?'<label>UPI ID<input id="upi" placeholder="name@upi"></label>':m==='Card'?'<label>Card Number<input id="card" maxlength="19" placeholder="1234 5678 9012 3456"></label>':'<label>Bank<select id="bank"><option>State Bank</option><option>HDFC Bank</option><option>ICICI Bank</option></select></label>'}
async function pay(){if(!pending)return alert('Complete passenger details first.');if(method==='UPI'&&!$('upi')?.value.trim())return alert('Enter UPI ID.');if(method==='Card'&&!$('card')?.value.trim())return alert('Enter card number.');const {data:b,error}=await supabaseClient.rpc('book_ticket',pending);if(error)return alert(error.message);const {data:p,error:pe}=await supabaseClient.rpc('record_payment',{p_ticket_number:b.ticket_number,p_method:method,p_amount:b.fare});if(pe)return alert(pe.message);$('ticket').classList.remove('hidden');$('ticketCard').innerHTML=`<h2>🎫 Ticket Generated</h2><p><span class="status">${escapeHtml(b.status)}</span></p><div class="ticketGrid"><div><small>Ticket</small><b>${b.ticket_number}</b></div><div><small>Passenger</small><b>${escapeHtml(b.passenger_name)}</b></div><div><small>Train</small><b>${escapeHtml(b.train_name)}</b></div><div><small>Route</small><b>${escapeHtml(b.route)}</b></div><div><small>Class</small><b>${b.travel_class}</b></div><div><small>Fare</small><b>₹${b.fare}</b></div></div><p>Payment Successful • ${method} • ${p.payment_id}</p>`;$('payment').classList.add('hidden');$('booking').classList.add('hidden');$('ticket').scrollIntoView({behavior:'smooth'});pending=null;await loadTrains();history()}
async function history(){if(!user){$('historyList').innerHTML='<div class="empty">Login to view bookings.</div>';return}const {data,error}=await supabaseClient.from('bookings').select('*').order('id',{ascending:false});if(error){$('historyList').innerHTML='<div class="empty">Could not load booking history.</div>';return}$('historyList').innerHTML=data?.length?data.map(x=>`<div class="row"><b>${x.ticket_number}</b><span>${escapeHtml(x.passenger_name)}</span><span>${escapeHtml(x.train_name)}</span><span>${x.travel_class}</span><span>${x.status}</span><span>${x.status!=='Cancelled'?`<button class="cancel" onclick="cancelTicket('${x.ticket_number}')">Cancel</button>`:'—'}</span></div>`).join(''):'<div class="empty">No bookings yet.</div>'}
async function cancelTicket(t){if(!confirm('Cancel this ticket?'))return;const {data,error}=await supabaseClient.rpc('cancel_ticket',{p_ticket_number:t});if(error)return alert(error.message);await loadTrains();history();alert('Ticket cancelled.')}
function modal(x){$('modalBody').innerHTML=x;$('modal').classList.remove('hidden')}function closeModal(){$('modal').classList.add('hidden')}
function login(msg=''){modal(`<h2>Login</h2><p>${escapeHtml(msg)}</p><form onsubmit="doLogin(event)"><label>Email<input id="le" type="email" required></label><label>Password<input id="lp" type="password" required></label><button class="primary">Login</button></form><p>New user? <a href="#" onclick="signup();return false">Sign up</a></p>`)}
async function doLogin(e){e.preventDefault();const {data,error}=await supabaseClient.auth.signInWithPassword({email:$('le').value.trim(),password:$('lp').value});if(error)return alert(error.message);await loadUser(data.user);closeModal();nav();history()}
function signup(){modal(`<h2>Create account</h2><form onsubmit="doSignup(event)"><label>Name<input id="sn" required></label><label>Email<input id="se" type="email" required></label><label>Mobile<input id="sm" maxlength="10" required></label><label>Password<input id="sp" type="password" minlength="4" required></label><button class="primary">Sign Up</button></form><p>Already registered? <a href="#" onclick="login();return false">Login</a></p>`)}
async function doSignup(e){e.preventDefault();const mo=$('sm').value.trim();if(!/^\d{10}$/.test(mo))return alert('Enter a valid 10-digit mobile number.');const {data,error}=await supabaseClient.auth.signUp({email:$('se').value.trim(),password:$('sp').value,options:{data:{name:$('sn').value.trim(),mobile:mo}}});if(error)return alert(error.message);if(!data.session)return alert('Account created. If email confirmation is enabled, confirm the email, then log in.');await loadUser(data.user);closeModal();nav();history();alert('Account created successfully.')}
async function logout(){await supabaseClient.auth.signOut();user=null;profile=null;nav();history()}
function nav(){$('loginNav').classList.toggle('hidden',!!user);$('logoutNav').classList.toggle('hidden',!user)}
async function adminLogin(){if(!user)return login('Login with your admin account.');const {data:p}=await supabaseClient.from('profiles').select('role').eq('id',user.id).single();if(p?.role==='ADMIN')location.href='admin.html';else alert('This account is not an admin account.')}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('from').addEventListener('keydown',e=>{if(e.key==='Enter')searchRoute()});$('to').addEventListener('keydown',e=>{if(e.key==='Enter')searchRoute()});$('query').addEventListener('keydown',e=>{if(e.key==='Enter')searchTrain()});init();
